SiteTitle: CoderJony
TwitterUsername: "@ankushjain358"
DefaultAuthor: "Ankush Jain"
FacebookPageUrl: "https://www.facebook.com/coderjony/"
FacebookAuthorUrl: "https://www.facebook.com/IamAnkushJain1990/"
DefaultImage: "https://coderjony.com/img/blogs/default.png"
Host:  coderjony.com
LinksUseHttps:  true
PageTitle: |
  =>
  {
    string siteTitle = Context.GetString("SiteTitle");
    string title = GetString("Title");
    return string.IsNullOrWhiteSpace(siteTitle) ? title : (string.IsNullOrWhiteSpace(title) ? siteTitle : $"{siteTitle} - {title}");
  }
Copyright: => $"Copyright © {DateTime.Now.Year}"
BlogSources: blogs/*.md
Layout: /_Layout.cshtml
PageSize: 8